Subiendo-rutas-y-Navbar
MilyRodz/final-project pull request #20
Opened 2021-03-17 14:54 UTC by luisrcc

2021-03-18 17:47 UTC, MilyRodz commented on src/front/styles/app.css
> +    border-color: blue;
Creo que lo mejor es utilizar clases nuevas, no sobrescribir las clases de bootstrap.

2021-03-20 00:44 UTC, MilyRodz requested changes
Crear una clase nueva para cambiar el estilo de .container

2021-03-20 00:44 UTC, MilyRodz commented on src/front/styles/app.css
> +.container {
Esto sobrescribe la clase container de Bootstrap

2021-03-23 22:10 UTC, MilyRodz approved these changes

2021-03-23 22:10 UTC, MilyRodz commented on src/front/js/component/ButtonRegister.js
> +    retunr(
hay un error en retuRn

2021-03-23 23:02 UTC, mortegac approved these changes

2021-03-23 23:02 UTC, merged